# Generated by Django 6.0.2 on 2026-02-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activiteit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('begintijd', models.TimeField()),
                ('eindtijd', models.TimeField()),
                ('omschrijving', models.TextField()),
                ('kosten', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['datum', 'begintijd'],
            },
        ),
    ]
