# Generated by Django 6.0.2 on 2026-02-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activiteit',
            options={'ordering': ['datum', 'begin_tijd']},
        ),
        migrations.RenameField(
            model_name='activiteit',
            old_name='begintijd',
            new_name='begin_tijd',
        ),
        migrations.RenameField(
            model_name='activiteit',
            old_name='eindtijd',
            new_name='eind_tijd',
        ),
    ]
